alt_stu_viz:
    resource: "@AltSTUVizBundle/Resources/config/routing.yml"
    prefix:   /

alt_stu_poll:
    resource: "@AltSTUPollBundle/Resources/config/routing.yml"
    prefix:   /

acme_store:
    resource: "@AcmeStoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

