<?php

namespace AltSTU\VizBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class VizController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AltSTU\VizBundle\Controller\VizController();
        return $instance;
    }
}
