parameters:
#    alt_stu_poll.example.class: AltSTU\PollBundle\Example

services:
#    alt_stu_poll.example:
#        class: %alt_stu_poll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
